### ISSUE TITLE
Triple click in textfield causing exception

### ISSUE THREAD

**Issue by Elime1** [orange451/LWJGUI#19]
A triple click in any textfield will cause a StringIndexOutOfBoundsException. 

It can be reproduced in TextAreaExample. Start the example and do three fast left mouse clicks in any text area - the app will crash.

```
Exception in thread "Thread-0" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at lwjgui.scene.control.TextInputControl$TextInputScrollPane.lambda$new$2(TextInputControl.java:1126)
	at lwjgui.event.EventHelper.fireEvent(EventHelper.java:15)
	at lwjgui.scene.Node.onMousePressed(Node.java:1235)
	at lwjgui.scene.Window.lambda$mouseButtonCallback$23(Window.java:1089)
	at lwjgui.scene.Window$1.call(Window.java:883)
	at lwjgui.scene.Window$1.call(Window.java:880)
	at lwjgui.Task.callI(Task.java:61)
	at lwjgui.scene.Window.render(Window.java:315)
	at lwjgui.scene.WindowThread.run(WindowThread.java:66)
```
This only happens if the text field is empty.

**Comment by Guerra24** [comment]
Sorry for the late fix! It should work now.
